engines:
  rubocop:
    enabled: true
    config: .hound.ruby.yml
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
    - crowbar_framework/**/*
    - chef/**/*
    - lib/**/*
    - bin/**/*

exclude_paths:
  - spec/**/*
  - vendor/**/*
